# Generated by Django 5.1.7 on 2025-03-25 06:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(default=api.models.generate_case_id, editable=False, max_length=10, unique=True)),
                ('case_title', models.CharField(blank=True, max_length=100, null=True)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('case_record', models.TextField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('finished_dt', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=100)),
                ('user_line_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'cases',
                'ordering': ['-created_dt'],
            },
        ),
    ]
