# Generated by Django 5.1.7 on 2025-04-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casemodel',
            old_name='user_id',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='casemodel',
            old_name='user_line_id',
            new_name='line_id',
        ),
        migrations.AddField(
            model_name='casemodel',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casemodel',
            name='service',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
