Resources:
  sslSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: { "Fn::GetAtt": ["AWSEBSecurityGroup", "GroupId"] }
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443
      CidrIp: 0.0.0.0/0
option_settings:
  aws:elasticbeanstalk:environment:process:default:
    Port: 443
    Protocol: HTTPS
    SSLCertificateArns: arn:aws:acm:ap-northeast-1:851725588449:certificate/48fe191d-d111-4dc4-a9bf-760611e9c8ed
  aws:elasticbeanstalk:application:environment:
    AWS_REGION: ap-northeast-1
