Resources:
  sslSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: { "Fn::GetAtt": ["AWSEBSecurityGroup", "GroupId"] }
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443
      CidrIp: 0.0.0.0/0
option_settings:
  aws:elasticbeanstalk:environment:process:default:
    Port: 443
    Protocol: HTTPS
    SSLCertificateArns: arn:aws:acm:us-east-1:851725588449:certificate/43f8c939-3614-4fb1-ad0e-9ef05767424d
  aws:elasticbeanstalk:application:environment:
    AWS_REGION: ap-northeast-1
