name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        env:
          MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
        run: |
          docker build \
            --build-arg MONGO_DB_USERNAME="$MONGO_DB_USERNAME" \
            --build-arg MONGO_DB_PASSWORD="$MONGO_DB_PASSWORD" \
            --build-arg MONGO_DB_NAME="$MONGO_DB_NAME" \
            --build-arg LINE_CHANNEL_SECRET="$LINE_CHANNEL_SECRET" \
            --build-arg LINE_CHANNEL_ACCESS_TOKEN="$LINE_CHANNEL_ACCESS_TOKEN" \
            --build-arg LINE_GROUP_ID="$LINE_GROUP_ID" \
            -t fordige/fordige-home:latest .
          docker push fordige/fordige-home:latest
          if [ $? -ne 0 ]; then
            echo "Failed to push Docker image"
            exit 1
          fi

      - name: Generate deployment package
        run: |
          ls -la .platform
          zip -r deploy.zip Dockerrun.aws.json .platform
          unzip -l deploy.zip
          aws s3 cp deploy.zip s3://elasticbeanstalk-ap-northeast-1-851725588449/fordige-application/deploy.zip
          sleep 10
          aws s3 ls s3://elasticbeanstalk-ap-northeast-1-851725588449/fordige-application/deploy.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name fordige-application \
            --version-label ${{ github.sha }}-${{ github.run_id }} \
            --source-bundle S3Bucket=elasticbeanstalk-ap-northeast-1-851725588449,S3Key=fordige-application/deploy.zip \
            --region ap-northeast-1
          aws elasticbeanstalk update-environment \
            --environment-name Fordige-application-env \
            --version-label ${{ github.sha }}-${{ github.run_id }} \
            --region ap-northeast-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
