name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        env:
          MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
        run: |
          docker build \
            --build-arg MONGO_DB_USERNAME="$MONGO_DB_USERNAME" \
            --build-arg MONGO_DB_PASSWORD="$MONGO_DB_PASSWORD" \
            --build-arg MONGO_DB_NAME="$MONGO_DB_NAME" \
            --build-arg LINE_CHANNEL_SECRET="$LINE_CHANNEL_SECRET" \
            --build-arg LINE_CHANNEL_ACCESS_TOKEN="$LINE_CHANNEL_ACCESS_TOKEN" \
            --build-arg LINE_GROUP_ID="$LINE_GROUP_ID" \
            -t fordige/fordige-home:latest .
          docker push fordige/fordige-home:latest
          if [ $? -ne 0 ]; then
            echo "Failed to push Docker image"
            exit 1
          fi

      - name: Generate deployment package
        run: |
          ls -la .platform
          zip -r deploy.zip Dockerrun.aws.json .platform
          unzip -l deploy.zip
          mkdir -p artifacts
          cp deploy.zip artifacts/
          ls -la artifacts

      - name: Upload deploy.zip for debugging
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: artifacts/deploy.zip
          retention-days: 7

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: fordige-application
          environment_name: Fordige-application-env
          version_label: ${{ github.sha }}-${{ github.run_id }}
          region: ap-northeast-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true
        env:
          MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
